### ISSUE TITLE
Difficulty choice/Datatext option

### ISSUE THREAD

**Issue by LiamGBR** [derfloh205/LoadoutReminder#1]
Different talents for a heroic and mythic boss since might want ST on one and cleave on another difficulty. 

Planning on replacing BtWLoadouts addon with this and it has something in ElvUI datatexts called LDB that displayed current "overall/group" name e.g. if you had talents named "Dungeons" and equipment "Outlaw" and the two would be under the group Mythic+
Since this is similar but automated was thinking maybe as an override option if on a boss you need to swap talents for more aoe/st as im not sure what happens if you change that on the blizzard talent page then target the boss.

also has other quick toggle settings which could be good to have something similar

![SBQT7j](https://github.com/derfloh205/LoadoutReminder/assets/26609549/06f87351-8900-467b-a127-683f6c03c7c4)

![O2Cv0K](https://github.com/derfloh205/LoadoutReminder/assets/26609549/9c669a29-15e8-4045-8433-23a7fc979136)

**Comment by derfloh205** [comment]
Difficulties are supported now with Version 5+
