### ISSUE TITLE
11.x Addon Error on Load

### ISSUE THREAD

**Issue by sudoalias** [derfloh205/LoadoutReminder#14]
Looks like there is an issue with the 11.0 API changes surrounding options/settings windows.  https://warcraft.wiki.gg/wiki/Patch_11.0.2/API_changes for reference.  Error on addon load:

 

2x LoadoutReminder/Init/Init.lua:63: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)

[string "@LoadoutReminder/Init/Init.lua"]:63: in function `InitOptionsPanel'

[string "@LoadoutReminder/Init/Init.lua"]:22: in function <LoadoutReminder/Init/Init.lua:16>

 

Locals:

self = Frame {

 READY = false

 FRAMES = <table> {

 }

}

optionsPanel = Frame {

 name = "LoadoutReminder"

 hint = <table> {

 }

}

(*temporary) = nil

(*temporary) = Frame {

 name = "LoadoutReminder"

 hint = <table> {

 }

}

(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

GGUI = <table> {

 Tab = <table> {

 }

 CustomDropdown = <table> {

 }

 CheckboxSelector = <table> {

 }

 BlizzardTabSystem = <table> {

 }

 ScrollFrame = <table> {

 }

 Dropdown = <table> {

 }

 Object = <table> {

 }

 FrameList = <table> {

 }

 Frame = <table> {

 }

 QualityIcon = <table> {

 }

 TabSystem = <table> {

 }

 SpellIcon = <table> {

 }

 HelpIcon = <table> {

 }

 ToggleButton = <table> {

 }

 TooltipOptionsFrame = <table> {

 }

 Texture = <table> {

 }

 BlizzardTab = <table> {

 }

 ScrollingMessageFrame = <table> {

 }

 Button = <table> {

 }

 Icon = <table> {

 }

 ClassIcon = <table> {

 }

 Checkbox = <table> {

 }

 NumericInput = <table> {

 }

 Text = <table> {

 }

 CurrencyInput = <table> {

 }

 TextInput = <table> {

 }

 ItemSelector = <table> {

 }

 CONST = <table> {

 }

 Widget = <table> {

 }

 Slider = <table> {

 }

}

f = <table> {

 a = "     "

 P = "|A:Professions-Icon-Quality-Tier3:15:15:0:0|a "

 s = "|A:Professions-Icon-Quality-Tier2:15:15:0:0|a "

 p = "|A:Professions-Icon-Quality-Tier1:15:15:0:0|a "

}

**Comment by sudoalias** [comment]
It appears the following change resolves the issue:
In LoadoutReminder\Init\Init.lua at line 63:

from:
`	InterfaceOptions_AddCategory(optionsPanel)`

to:
`	local category = Settings.RegisterCanvasLayoutCategory(optionsPanel, "LoadoutReminder")
	Settings.RegisterAddOnCategory(category)`

**Comment by derfloh205** [comment]
fixed in 6.2.0
