### ISSUE TITLE
Popup shows in combat

### ISSUE THREAD

**Issue by filliph** [derfloh205/LoadoutReminder#4]
If you change the loadout from what you define in the settings, the popup will come back every time you target the boss even in combat.

Needless to say, a black box in the middle of your screen mid combat is not helpful 🙂

**Comment by derfloh205** [comment]
Question is should it baseline just not show in combat or should it be a toggleable option 🤔

**Comment by derfloh205** [comment]
Fixed with 4.2.1

LoadoutReminder will not check your loadout sets within combat but will check once you get out of combat
